create table buy_request (id integer not null auto_increment, post_id integer, status_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table locations (id integer not null auto_increment, user_id integer, city varchar(255), door_number varchar(255), flat_number varchar(255), neighborhood varchar(255), state varchar(255), street varchar(255), primary key (id)) engine=InnoDB;
create table post_image (id integer not null auto_increment, post_id integer, url varchar(255), primary key (id)) engine=InnoDB;
create table posts (id integer not null auto_increment, detail varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table status (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (id integer not null auto_increment, name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
alter table buy_request add constraint UK_sbh8use5wdqy714mbuelmuepm unique (status_id);
alter table buy_request add constraint FK11regk7pxjsvdugu3eqlj34bq foreign key (post_id) references posts (id);
alter table buy_request add constraint FKnyhp82vbpggdx2txhkkv79qub foreign key (status_id) references status (id);
alter table buy_request add constraint FKk7goyqgsnu1i5dx5e9rs8vyct foreign key (user_id) references users (id);
alter table locations add constraint FKdmtxqhxbtg4qt8q6u01hxj52i foreign key (user_id) references users (id);
alter table post_image add constraint FKhrus3ul2vq1q2psp1l1y4mavd foreign key (post_id) references posts (id);
create table buy_request (id integer not null auto_increment, post_id integer, status_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table locations (id integer not null auto_increment, user_id integer, city varchar(255), door_number varchar(255), flat_number varchar(255), neighborhood varchar(255), state varchar(255), street varchar(255), primary key (id)) engine=InnoDB;
create table post_image (id integer not null auto_increment, post_id integer, url varchar(255), primary key (id)) engine=InnoDB;
create table posts (id integer not null auto_increment, detail varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table status (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (id integer not null auto_increment, name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
alter table buy_request add constraint UK_sbh8use5wdqy714mbuelmuepm unique (status_id);
alter table buy_request add constraint FK11regk7pxjsvdugu3eqlj34bq foreign key (post_id) references posts (id);
alter table buy_request add constraint FKnyhp82vbpggdx2txhkkv79qub foreign key (status_id) references status (id);
alter table buy_request add constraint FKk7goyqgsnu1i5dx5e9rs8vyct foreign key (user_id) references users (id);
alter table locations add constraint FKdmtxqhxbtg4qt8q6u01hxj52i foreign key (user_id) references users (id);
alter table post_image add constraint FKhrus3ul2vq1q2psp1l1y4mavd foreign key (post_id) references posts (id);
create table buy_request (id integer not null auto_increment, post_id integer, status_id integer, user_id integer, primary key (id)) engine=InnoDB;
create table locations (id integer not null auto_increment, user_id integer, city varchar(255), door_number varchar(255), flat_number varchar(255), neighborhood varchar(255), state varchar(255), street varchar(255), primary key (id)) engine=InnoDB;
create table post_image (id integer not null auto_increment, post_id integer, url varchar(255), primary key (id)) engine=InnoDB;
create table posts (id integer not null auto_increment, detail varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table status (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (id integer not null auto_increment, name varchar(255), surname varchar(255), primary key (id)) engine=InnoDB;
alter table buy_request add constraint UK_sbh8use5wdqy714mbuelmuepm unique (status_id);
alter table buy_request add constraint FK11regk7pxjsvdugu3eqlj34bq foreign key (post_id) references posts (id);
alter table buy_request add constraint FKnyhp82vbpggdx2txhkkv79qub foreign key (status_id) references status (id);
alter table buy_request add constraint FKk7goyqgsnu1i5dx5e9rs8vyct foreign key (user_id) references users (id);
alter table locations add constraint FKdmtxqhxbtg4qt8q6u01hxj52i foreign key (user_id) references users (id);
alter table post_image add constraint FKhrus3ul2vq1q2psp1l1y4mavd foreign key (post_id) references posts (id);
